## 本番環境設定

# サイト設定
title: "サイト名を入力します"
excerpt: "meta descriptionを入力します"
url: "https://yourdomain.com" # サイトURL (OGタグ出力のため)

# Social
# socialimg: /img/common/og_default.png
# facebook: facebook_username
# facebook_appid: facebook_appid
# twitter: twitter_username

## Asset
dir_css: "/css/"
dir_js: "/js/"
dir_img: "/img/"

sass:
  sass_dir: css
  style: :compressed

## HTML圧縮
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  ignore:
    envs: [local]
  startings: [html, head, body]

exclude: [.scss, README.md, node_modules, gruntfile.js, package.json, Gemfile, Gemfile.lock, memo.steplog]
